build.gradle
=> Added support IntelliJ IDEA

build.gradle, gradle.properties, src/main/groovy/com/marklogic/gradle/task/MlcpTask.groovy
=> add output_type parameter

build.gradle
=> Add plugin to generate dependency report for legal

src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy, src/main/groovy/com/marklogic/gradle/task/MarkLogicTask.groovy, src/main/groovy/com/marklogic/gradle/task/roxy/MLRoxyCopyProperties.groovy
@rjrudin mlRoxyCopyProperties task, I'm not expecting this to be accurate. This could be good starting point to at least understand the PR workflow. Please take a look at and let me know.
=> mlRoxyCopyProperties task

gradle.properties, src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy, src/main/groovy/com/marklogic/gradle/task/roxy/RoxyGenerateTestScaffoldTask.groovy, src/main/groovy/com/marklogic/gradle/task/roxy/RoxyGenerateTestSuiteTask.groovy, src/main/groovy/com/marklogic/gradle/task/roxy/scaffoldTemplates/SampleTestFiles.groovy
Second attempt at creating a task to generate Roxy test suites.
=> Feature/roxy test/ft rt6

examples/unit-test-project/gradle.properties
Updating dependency to latest version of marklogic-unit-test
=> marklogic-unit-test 1.0.0

examples/jsdoc-project/README.md, examples/jsdoc-project/build.gradle, examples/jsdoc-project/gradle.properties
=> Update jsDoc example to use latest versions (Take 2)

examples/docker-projects/three-node-cluster-with-ha-proxy/src/main/docker/marklogic/Dockerfile
Commented the converter package options
=> Updated Dockerfile

examples/corb2-project/build.gradle, examples/corb2-project/gradle.properties
=> update to latest CoRB release 2.5.3

examples/mlcp-project/build.gradle
Changes to upgrade MLCP to 10.0.9 and exclude log4j dependencies
=> Resolves issue #610

examples/ssl-project/build.gradle, src/main/groovy/com/marklogic/gradle/task/DeleteModuleTimestampsFileTask.groovy
Made filePath a class property and added @Input and added @Optional annotation on filePath
=> #617 fixed issue with mlDeleteModuleTimestampsFile

examples/corb2-project/gradle/wrapper/gradle-wrapper.properties, examples/docker-projects/single-node/gradle/wrapper/gradle-wrapper.properties, examples/entity-services-project/gradle/wrapper/gradle-wrapper.properties, examples/external-security/gradle/wrapper/gradle-wrapper.properties, examples/failover-project/gradle/wrapper/gradle-wrapper.properties, examples/flexrep-project/gradle/wrapper/gradle-wrapper.properties, examples/flexrep-with-path-project/gradle/wrapper/gradle-wrapper.properties, examples/httpbuilder-project/gradle/wrapper/gradle-wrapper.properties, examples/ignore-resources-project/gradle/wrapper/gradle-wrapper.properties, examples/mimetypes-project/gradle/wrapper/gradle-wrapper.properties, examples/minimal-project/gradle/wrapper/gradle-wrapper.properties, examples/no-appservers-project/gradle/wrapper/gradle-wrapper.properties, examples/properties-project/gradle/wrapper/gradle-wrapper.properties, examples/redaction-ruleset-project/gradle/wrapper/gradle-wrapper.properties, examples/role-project/gradle/wrapper/gradle-wrapper.properties, examples/sample-project/gradle/wrapper/gradle-wrapper.properties, examples/schemas-project/gradle/wrapper/gradle-wrapper.properties, examples/shell-project/gradle/wrapper/gradle-wrapper.properties, examples/ssl-2way-project/gradle/wrapper/gradle-wrapper.properties, examples/ssl-project/gradle/wrapper/gradle-wrapper.properties, examples/temporal-lsqt-project/gradle/wrapper/gradle-wrapper.properties, examples/temporal-project/gradle/wrapper/gradle-wrapper.properties, examples/uni-temporal-project/gradle/wrapper/gradle-wrapper.properties, examples/use-modulesdb-project/gradle/wrapper/gradle-wrapper.properties
typo in distributionUrl of gradle wrapper properties file
=> #616 fixed issue in distributionUrl for gradle wrapper

README.md, build.gradle, examples/alert-project/build.gradle, examples/cpf-project/build.gradle, examples/data-services/build.gradle, examples/disconnected-project-using-plugins-and-gradlew/build.gradle, examples/local-testing-project/gradle.properties, examples/mlcp-project/build.gradle, examples/redaction-ruleset-project/build.gradle, examples/roxy-project/build.gradle, examples/sample-project/build.gradle, examples/schemas-project/build.gradle, examples/ssl-project/build.gradle, examples/triggers-project/build.gradle, examples/unit-test-project/gradle.properties, pom.xml, src/main/groovy/com/marklogic/gradle/task/NewProjectTask.groovy
To be merged after the other PRs for 4.3.5
=> Bumped to 4.3.5

build.gradle
Results in using jackson-databind 2.12.7.1
=> Bumped to ml-app-deployer 4.3.7

build.gradle, examples/jdbc-project/build.gradle
Done via transitive dependencies
=> Bumped Spring to 5.3.27

src/main/groovy/com/marklogic/gradle/task/test/UnitTestTask.groovy
Can't refer to an mlut class in a method signature since's a compileOnly dependency.
=> Fixing issue in mlUnitTest

CONTRIBUTING.md, ml-gradle/src/main/groovy/com/marklogic/gradle/task/client/generator/SjsTransformGenerator.java, ml-gradle/src/main/groovy/com/marklogic/gradle/task/client/generator/XqueryTransformGenerator.java, ml-gradle/src/main/groovy/com/marklogic/gradle/task/client/generator/XslTransformGenerator.java, ml-gradle/src/test/groovy/com/marklogic/gradle/GenerateTransformWithRedactionTask.groovy, ml-javaclient-util-test-app/.gitignore, ml-javaclient-util-test-app/docker-compose.yaml, ml-javaclient-util-test-app/src/main/ml-data/jane.json, ml-javaclient-util-test-app/src/main/ml-schemas/redaction-rules/collections.properties, ml-javaclient-util-test-app/src/main/ml-schemas/redaction-rules/email.json
Now uses the deployment from ml-javaclient-util-test-app.
=> Updated the transform testing

Jenkinsfile, build.gradle, gradle/wrapper/gradle-wrapper.properties, ml-app-deployer/build.gradle, ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/plugins/InstallPluginsCommand.java, ml-app-deployer/src/main/java/com/marklogic/mgmt/api/API.java, ml-gradle/build.gradle, ml-javaclient-util/build.gradle, ml-javaclient-util/src/main/java/com/marklogic/client/ext/es/EntityServicesManager.java, ml-javaclient-util/src/main/java/com/marklogic/client/ext/file/PropertiesDrivenDocumentFileProcessor.java, ml-javaclient-util/src/main/java/com/marklogic/client/ext/qconsole/impl/DefaultWorkspaceManager.java, ml-javaclient-util/src/main/java/com/marklogic/client/ext/qconsole/impl/QconsoleScripts.java
Also bumped up some minor/patch dependency versions where possible.
=> Fixing Polaris high issues

ml-app-deployer/src/main/java/com/marklogic/rest/util/ResourcesFragment.java
Polaris reported two issues on this.
=> MLE-21542 Sanitizing values for XPath expressions

ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/AbstractCommand.java, ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/AbstractResourceCommand.java, ml-app-deployer/src/main/java/com/marklogic/mgmt/selector/AbstractNameMatchingResourceSelector.java
The one in AbstractCommand should knock out a lot of warnings.
=> MLE-21542 First batch of null checks

Jenkinsfile, build.gradle, gradle/wrapper/gradle-wrapper.properties, ml-app-deployer/build.gradle, ml-app-deployer/src/main/java/com/marklogic/rest/util/PreviewInterceptor.java, ml-app-deployer/src/test/java/com/marklogic/rest/util/PreviewInterceptorTest.java, ml-gradle/build.gradle, ml-javaclient-util/build.gradle
Not sure if this will be 5.1.0 or 6.0.0. But want to see all the tests pass.
Bumped up a number of other minor dependencies too.
=> MLE-22526 Bumping to Spring 6 and Java 17

build.gradle, examples/local-testing-project/gradle.properties, ml-app-deployer/src/main/java/com/marklogic/appdeployer/AppConfig.java, ml-app-deployer/src/main/java/com/marklogic/appdeployer/DefaultAppConfigFactory.java, ml-app-deployer/src/main/java/com/marklogic/mgmt/resource/security/CertificateTemplateManager.java, ml-javaclient-util/src/main/java/com/marklogic/client/ext/file/DefaultDocumentFileReader.java, ml-javaclient-util/src/main/java/com/marklogic/client/ext/ssl/SslUtil.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/ssl/SslUtilTest.java
Major number bump due to higher JVM requirement.
=> MLE-12345 Bumping version to 6.0-SNAPSHOT

NOTICE.txt, ml-gradle/build.gradle, ml-javaclient-util/build.gradle, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/AbstractDataMovementTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/UrisQueryQueryBatcherBuilderTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/DeleteCollectionsTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/DeleteTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ExportBatchesToDirectoryTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ExportBatchesToZipsTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ExportDocumentsToFilesTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ExportDocumentsToSingleFileTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ExportJsonToJsonFileTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ExportToZipTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ManageCollectionsTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ManagePermissionsTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/job/ParseTransformPropertyValueTest.java, ml-javaclient-util/src/test/java/com/marklogic/client/ext/datamovement/listener/XmlOutputListenerTest.java
And a few copyright updates too.
=> MLE-22591 Bumped a couple dependencies and updated NOTICE

.copyrightconfig, ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/temporal/DeployTemporalCollectionsLSQTCommand.java, ml-app-deployer/src/test/java/com/marklogic/appdeployer/AbstractAppDeployerTest.java, ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/temporal/DeployTemporalTest.java, ml-app-deployer/src/test/resources/sample-app/temporal-config-with-lsqt/databases/other-sample-app-content/temporal/collections/lsqt/temporal-collection.json, ml-app-deployer/src/test/resources/sample-app/temporal-config-with-lsqt/databases/other-sample-app-content/temporal/collections/lsqt/temporal-collection.xml
Introduced in 6.0.0 during refactor, due to missing test on the LSQT document being created.
=> MLE-24511 Fixing bug with updating LSQT properties
