marklogic/ml-gradle

- src/main/groovy/com/rjrudin/marklogic/gradle/MarkLogicPlugin.groovy
Jim - instead of quieting the init messages, I just made them log messages at the info level, which gives the user control over whether they show up or not - i.e. whether Gradle is run with "-i" or "--info".
> #19 ml-gradle init messages should be quiet if not running ml-gradle

- examples/corb2-project/build.gradle
- examples/corb2-project/build/ml-last-configured-timestamps.properties
- examples/corb2-project/gradle.properties
- examples/corb2-project/src/main/ml-modules/ext/corb2-project/corb/options.properties
- examples/corb2-project/src/main/ml-modules/ext/corb2-project/corb/transform.xqy
- examples/corb2-project/src/main/ml-modules/ext/corb2-project/corb/uris.xqy
- src/main/groovy/com/marklogic/gradle/task/CorbTask.groovy
Added explicit fields for each of the CoRB2 options, the ability to set
project properties (with naming convention to prevent conflicts),
and/or System properties. CoRB options are now set using System
properties, allowing for any/all of the options to be specified when
executing the CorbTask.
Project properties use the naming convention of a “corb” prefix and
CamelCased name of the option (i.e. -PcorbThreadCount would set
THREAD-COUNT).
System properties will look for CoRB options with their original names
(i.e. -DTHREAD-COUNT).
Previous CorbTask member variables and behavior were preserved, such as
the convention of constructing the URIS-MODULE and PROCESS-MODULE if
modulePrefix value is specified.
Methods to collect and overlay the CoRB options are extracted into
methods that can be …
> resolves #69

- .gitignore
- build.gradle
- examples/corb2-project/build.gradle
- examples/mlcp-project/build.gradle
- examples/sample-project/build.gradle
- src/main/groovy/com/marklogic/gradle/task/CorbTask.groovy
- Updated CoRB references to 2.3.0
- Changed the CorbTask to attempt to obtain the list of CoRB options from the Options class. If not available, uses default list of options.
- Bumped the bintray plugin version to 1.6
> Update CorbTask to 2.3.0 and ability to dynamically enhance CorbTask with CoRB Options

- examples/mlcp-project/build.gradle
Marklogic seems to have updated their repo to use https. The server was returning a `401: Authorization Required` error when the mlcp dependency was attempting to be accessed via http thus causing the build to fail.
> update mlcp dependency to use https over http

- src/main/groovy/com/marklogic/gradle/task/CorbTask.groovy
Rather than only selecting the system properties that match known CoRB
option names, collect all system properties and pass to CoRB. This
allows for xcc.httpcompliant to be set, as well as any custom inputs
(e.g. PROCESS-MODULE.foo, URIS-MODULE.bar, etc).
Resolves issue #146 and issue #128
> CHANGED: collect all system properties to send to CoRB

- README.md
The intent of this is to slim down the project README page to the following:
1. A brief explanation of what ml-gradle is used for 
1. Links to more information and docs
1. A brief tutorial to get someone new to ml-gradle familiar with ml-gradle as quickly as possible
The goal for the project README page then is to quickly explain and show what ml-gradle is for a new user so they can understand whether ml-gradle can help them or not. 
You can view the new README on its branch at https://github.com/marklogic-community/ml-gradle/blob/feature/new-readme/README.md 
The content removed from the current README page will  move to the Wiki home page, which will then serve two purposes:
1. Provide a more useful outline to ml-gradle docs than what it is provided by the Wiki index on the right
1. …
> New project README page

- gradle/wrapper/gradle-wrapper.properties
- src/main/groovy/com/marklogic/gradle/task/MarkLogicTask.groovy
- src/main/groovy/com/marklogic/gradle/task/databases/DeleteUserSchemasTask.groovy
Fixes https://github.com/marklogic/marklogic-data-hub/issues/1716
> Delete user schemas from user schemas database only

- src/main/groovy/com/marklogic/gradle/task/test/UnitTestTask.groovy
- src/test/groovy/com/marklogic/gradle/UnitTestTaskTest.groovy
Fixing https://github.com/marklogic-community/marklogic-unit-test/issues/75
Fixing a bug when writing test result XML for nested test
suites.  Originally the '/' or '\\' in the suite path would
be treated as a separate directory by Groovy, which was
throwing file not found errors as those directories did not
exist on the local file system.  Now the task will replace
directory separators with '_' when writing the XUnit XML.
> Test Results for Nested Test Suites

- src/main/groovy/com/marklogic/gradle/task/client/CallResourceTask.groovy
I built and tested this locally and it looks like it works. The `callResource` function already checks whether `client == null` and initializes it if so.
> #558 Defer creating client until task is run

- examples/mlcp-project/build.gradle
- examples/mlcp-project/lib/log4j.properties
- examples/mlcp-project/lib/logback.xml
The mlcp dependency no longer excludes anything. This will result in SLF4J warning about multiple bindings, but the logback logging will still work. Getting rid of that warning is possible, but does not seem worth the complexity in build.gradle.
> 629: Changed MLCP example project to use logback

- build.gradle
- examples/local-testing-project/gradle.properties
- src/main/groovy/com/marklogic/gradle/task/NewProjectTask.groovy
Also bumped version to 4.4-SNAPSHOT
> #636 Clarified instructions in mlNewProject

- src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy
- src/main/groovy/com/marklogic/gradle/task/security/DeployHostCertificateTemplatesTask.groovy
Verified manually with sample files in ml-app-deployer project
> DEVEXP-151: Added task for deploying host certificate templates

- examples/custom-forests-and-replicas-project/build.gradle
- src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy
- src/main/groovy/com/marklogic/gradle/task/forests/PrintForestPlanTask.groovy
This was not accounting for the fact that the "deployForestsCommand" will be null when a user is explicitly creating forests instead of dynamically creating them via properties.
> DEVEXP-183: Fixing bug in mlPrintForestPlan

- src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy
- src/main/groovy/com/marklogic/gradle/task/test/GenerateUnitTestSuiteTask.groovy
Added a `-Planguage` parameter to the `mlGenerateUnitTestSuite` task. Accepts either "sjs" or "xqy". It looks for "sjs" and generates a JavaScript test suite if it matches; otherwise assumes XQuery. Also assumes XQuery if the parameter is missing (to maintain previous behavior).
> Add language parameter to mlGenerateUnitTestSuite

- examples/ssl-2way-project/build.gradle
The previous version used ml-gradle 3.x and Java Client 4. With ml-gradle 4.x using Java Client 5 and higher, an X509TrustManager must be explicitly provided (has to do with the Java Client changing from using Apache HTTP to OkHttp between major versions 4 and 5). Setting `restTrustManager` accomplishes that. 
Also had to bump up the SSL version to the standard TLSv1.2.
This project will receive more updates soon so that it is easier to test with.
> Updated ssl-2way to work with ml-gradle 4.x

- examples/ssl-project/README.md
- examples/ssl-project/gradle.properties
- examples/ssl-project/src/main/ml-config/servers/README.md
- examples/ssl-project/src/main/ml-config/servers/rest-api-server.json
In some previous version of MarkLogic, support was added for a certificate template name in a server JSON file, so we don't need the trick anymore of referencing the ID of a certificate template.
> Updating the ssl-project example

- src/main/groovy/com/marklogic/gradle/task/NewProjectTask.groovy
- src/main/groovy/com/marklogic/gradle/task/scaffold/GenerateScaffoldTask.groovy
This PR will work after https://github.com/marklogic/ml-app-deployer/pull/489 is merged.
> DEVEXP-427: Generate schemas database when running mlNewProject

- examples/mlcp-project/build.gradle
- examples/mlcp-project/mlcpOptions.txt
- src/main/groovy/com/marklogic/gradle/task/MlcpTask.groovy
Tested manually with a few different gradle tasks and options_files.
Such as:
task importSampleDataWithOptionsFileWithHostUsernamePassword(type: com.marklogic.gradle.task.MlcpTask) {
classpath = configurations.mlcp
command = "IMPORT"
options_file = "mlcpOptionsHostUsernamePassword.txt"
}
> DEVEXP-258: Only set arguments not provided by options file when using MlcpTask

- build.gradle
- examples/unit-test-project/README.md
- examples/unit-test-project/gradle.properties
- src/main/groovy/com/marklogic/gradle/MarkLogicPlugin.groovy
- src/main/groovy/com/marklogic/gradle/task/test/UnitTestTask.groovy
Updated the unit-test project temporarily with snapshot dependencies for easy local testing before the release. 
Cleaned up UnitTestTask a bit by extracting a couple methods.
> DEVEXP-547 Can now select suites and tests to run

- src/main/groovy/com/marklogic/gradle/task/test/UnitTestTask.groovy
Adding "file://" makes the link clickable in an IDE like Intellij, just like how it works when "./gradlew test" fails.
> Friendlier error message when mlUnitTest bombs

- examples/corb2-project/build.gradle
- examples/corb2-project/gradle.properties
CoRB 2.5.5, which now has more simple gradle modules, so dependency no longer needs usage attributes to be set.
Remove explicit XCC dependency, rely on transitive
> Update to CoRB 2.5.5

- src/main/groovy/com/marklogic/gradle/task/DeployToReplicaTask.groovy
Correctly constructing a deployer. Verified no other occurrences existed of using the deprecated SimpleAppDeployer constructor.
> DEVEXP-626 Fixed DeployToReplicaTask

- src/main/groovy/com/marklogic/gradle/task/DeleteModuleTimestampsFileTask.groovy
No longer throws an error when `mlModuleTimestampsPath` is null or empty. Verified manually.
> DEVEXP-634 Fixed deletion of module timestamps file

- build.gradle
- examples/local-testing-project/build.gradle
- gradle/wrapper/gradle-wrapper.properties
With the update to the Gradle publishing plugin, something changed such that declaring `artifact sourcesJar` and `artifact javadocJar` caused Gradle to complain about multiple artifacts with the same extension. They appear unnecessary now, so I removed them, so that local publishing works again. Will revisit when it's time to publish to Maven Central.
> Updated Gradle config

- ml-app-deployer/src/main/java/com/marklogic/appdeployer/DefaultAppConfigFactory.java
- ml-app-deployer/src/main/java/com/marklogic/mgmt/DefaultManageConfigFactory.java
- ml-app-deployer/src/main/java/com/marklogic/mgmt/admin/DefaultAdminConfigFactory.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/DefaultAppConfigFactoryTest.java
I can't think of why this wasn't done before nor what the downside would be to not applying empty strings. Want to see the tests run to see if it causes any failures, implying that this would not be a backwards compatible change.
> Requiring property values to not be empty

- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/DeployForestsCommand.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestBuilder.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestPlan.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestReplicaPlanner.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ZoneAwareReplicaBuilderStrategy.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/forests/BuildForestReplicaTest.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/forests/BuildForestTest.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/forests/PlanForestReplicasTest.java
This isn't fully baked yet, but it gets the plumbing in place for accounting for a zone value on each host. ForestReplicaPlanner was created almost entirely by Copilot, and it's handling the work of determining which replicas to build and on what hosts.
Next step will be to enhance DeployForestsCommand to actually build the map of hosts to zones, which will then enable the feature.
A final step, and in a separate ticket, will be to figure out what to do with ConfigureForestReplicasCommand. That hopefully is no longer needed, given that DeployForestsCommand is able to create replicas as well.
> MLE-20741 Forest replica creation now considers host zone

- docker-compose.yaml
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ConfigureForestReplicasCommand.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/DeployForestsCommand.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestPlan.java
- ml-app-deployer/src/main/java/com/marklogic/mgmt/resource/hosts/HostManager.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/forests/ConfigureForestReplicasDebug.java
This hooks up the host-to-zone mapping so that it's fed into the forest replica planner. Currently only being tested via manual testing, which is consistent with how "real" replicas have been created in the past.
Enhanced the docker-compose file to create a 6-host cluster for manual testing purposes.
Story isn't quite done though. Need to add some tests for creating forests on a single host, as that seems a bit off.
> MLE-20741 Now accounting for zones when creating forest replicas

- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/databases/DeployOtherDatabasesCommand.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ConfigureForestReplicasCommand.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/DefaultHostCalculator.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/DeployForestsCommand.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/DistributedReplicaBuilderStrategy.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestBuilder.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestHostNames.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestPlan.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ForestPlanner.java
- ml-app-deployer/src/main/java/com/marklogic/appdeployer/command/forests/ZoneAwareReplicaBuilderStrategy.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/forests/BuildForestReplicaTest.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/forests/CreateForestsOnOneHostTest.java
- ml-app-deployer/src/test/java/com/marklogic/appdeployer/command/forests/CreateForestsOnSpecificHostsTest.java
Removed replica creation from DeployForestsCommand. ForestPlanner now handles both forests and replicas for the sake of previewing forest creation.
There's a lot more that can be done here - namely, in moving logic out of the command classes into a "forest calculator" class that handles all the logic for building and optionally saving a set of forests. But this at least gets rid of the two paths for replica creation.
> MLE-22812 Refactor: Only configuring replicas in one place

- ml-app-deployer/src/main/java/com/marklogic/rest/util/RestConfig.java
- ml-app-deployer/src/main/java/com/marklogic/rest/util/RestTemplateUtil.java
- ml-app-deployer/src/test/java/com/marklogic/mgmt/AbstractMgmtTest.java
- ml-app-deployer/src/test/java/com/marklogic/rest/util/RetryInterceptor.java
- ml-app-deployer/src/test/java/com/marklogic/rest/util/TestConfig.java
This really needs to be supported in the Java Client in order for it to be done correctly - specifically in the DatabaseClientBuilder class. Otherwise we can only support it in here for the Manage/Admin connections but not the REST / App-Services connections.
Had to move TestConfig so that it could invoke the protected method for specifying a ClientConfigurator, which thus keeps it out of the public API.
> MLE-23174 Hiding retry capability for now

- README.md
Mostly pointing to Getting Started guide now.
> MLE-22951 Updated README

- ml-app-deployer/src/main/java/com/marklogic/mgmt/ManageClient.java
- ml-app-deployer/src/test/java/com/marklogic/mgmt/ManageClientTest.java
Also deprecating the RestTemplate constructors and the setters for ManageConfig and RestTemplate so that ManageConfig can be made final in 7.0.
> MLE-23425 Better error when ManageConfig is null
